attorneys = read.csv("attorneys.csv")
attorneytimeentries = read.csv("attorneytimeentries.csv")
categories = read.csv("categories.csv")
clients = read.csv("clients.csv")
questionposts = read.csv("questionposts.csv")
questions = read.csv("questions.csv")
statesites = read.csv("statesites.csv")
subcategories = read.csv("subcategories.csv")
questions$Category = as.factor(questions$Category)
questionscategory = c(sum(questions$Category == "Family and Children"),
                      sum(questions$Category == "Individual Rights"),
                      sum(questions$Category == "Housing and Homelessness"),
                      sum(questions$Category == "Consumer Financial Questions"),
                      sum(questions$Category == "Other"),
                      sum(questions$Category == "Health and Disability"),
                      sum(questions$Category == "Income Maintenance"),
                      sum(questions$Category == "Work, Employment and Unemployment"),
                      sum(questions$Category == "Juvenile"),
                      sum(questions$Category == "Education")
)
barplot(questionscategory, main="Amount of Questions asked by Category", xlab="Categories",
        ylab="Amount of Questions", names.arg=c("FC", "IR",
                                                "HH",
                                                "CFQ", "O",
                                                "HD", "IM",
                                                "WEU",
                                                "J", "E"),
        col=rainbow(10)
        )
questions$StateAbbr = as.factor(questions$StateAbbr)
FC = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
IR = questions[questions$Category != "Family and Children" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
HH = questions[questions$Category != "Individual Rights" & questions$Category != "Family and Children" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
CFQ = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Family and Children" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
HD = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Family and Children",]
IM = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Family and Children" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
WEU = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Juvenile" & questions$Category != "Family and Children" & questions$Category != "Health and Disability",]
J = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Education" & questions$Category != "Family and Children" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
E = questions[questions$Category != "Individual Rights" & questions$Category != "Housing and Homelessness" & questions$Category != "Income Maintenance" & questions$Category != "Consumer Financial Questions" & questions$Category != "Other" & questions$Category != "Family and Children" & questions$Category != "Juvenile" & questions$Category != "Work, Employment and Unemployment" & questions$Category != "Health and Disability",]
FCstates = c(sum(FC$StateAbbr == "AL"),
             sum(FC$StateAbbr == "AK"),
             sum(FC$StateAbbr == "AZ"),
             sum(FC$StateAbbr == "AR"),
             sum(FC$StateAbbr == "CA"),
             sum(FC$StateAbbr == "CO"),
             sum(FC$StateAbbr == "CT"),
             sum(FC$StateAbbr == "DE"),
             sum(FC$StateAbbr == "DC"),
              sum(FC$StateAbbr == "FL"),
              sum(FC$StateAbbr == "GA"),
             sum(FC$StateAbbr == "HI"),
             sum(FC$StateAbbr == "ID"),
              sum(FC$StateAbbr == "IL"),
              sum(FC$StateAbbr == "IN"),
             sum(FC$StateAbbr == "IA"),
             sum(FC$StateAbbr == "KS"),
             sum(FC$StateAbbr == "KY"),
             sum(FC$StateAbbr == "LA"),
             sum(FC$StateAbbr == "ME"),
              sum(FC$StateAbbr == "MA"),
             sum(FC$StateAbbr == "MI"),
             sum(FC$StateAbbr == "MN"),
             sum(FC$StateAbbr == "MS"),
              sum(FC$StateAbbr == "MO"),
             sum(FC$StateAbbr == "MT"),
             sum(FC$StateAbbr == "NE"),
             sum(FC$StateAbbr == "NH"),
             sum(FC$StateAbbr == "NV"),
             sum(FC$StateAbbr == "NJ"),
             sum(FC$StateAbbr == "NM"),
             sum(FC$StateAbbr == "NY"),
             sum(FC$StateAbbr == "NC"),
             sum(FC$StateAbbr == "ND"),
             sum(FC$StateAbbr == "OH"),
             sum(FC$StateAbbr == "OK"),
             sum(FC$StateAbbr == "OR"),
             sum(FC$StateAbbr == "PA"),
             sum(FC$StateAbbr == "RI"),
              sum(FC$StateAbbr == "SC"),
             sum(FC$StateAbbr == "SD"),
              sum(FC$StateAbbr == "TN"),
              sum(FC$StateAbbr == "TX"),
             sum(FC$StateAbbr == "UT"),
             sum(FC$StateAbbr == "VT"),
             sum(FC$StateAbbr == "VA"),
             sum(FC$StateAbbr == "WA"),
             sum(FC$StateAbbr == "WV"),
              sum(FC$StateAbbr == "WI"),
             sum(FC$StateAbbr == "WY"),
             sum(FC$StateAbbr == "MD")
             )
FCstates2 = c(sum(FC$StateAbbr == "IN"),
              sum(FC$StateAbbr == "TX"),
              sum(FC$StateAbbr == "FL"),
              sum(FC$StateAbbr == "IL"),
              sum(FC$StateAbbr == "SC"),
              sum(FC$StateAbbr == "TN"),
              sum(FC$StateAbbr == "MO"),
              sum(FC$StateAbbr == "GA"),
              sum(FC$StateAbbr == "WI"),
              sum(FC$StateAbbr == "MA")
              )
FCstates2
barplot(FCstates2, main="Family and Children Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("IN", "TX", "FL", "IL",
                                                "SC", "TN", "MO", "GA",
                                                "WI", "MA"),
        col = rainbow(10)
        )

Estates = c( sum(E$StateAbbr == "AL"),
             sum(E$StateAbbr == "AK"),
             sum(E$StateAbbr == "AZ"),
             sum(E$StateAbbr == "AR"),
             sum(E$StateAbbr == "CA"),
             sum(E$StateAbbr == "CO"),
             sum(E$StateAbbr == "CT"),
             sum(E$StateAbbr == "DE"),
             sum(E$StateAbbr == "DC"),
              sum(E$StateAbbr == "FL"),
             sum(E$StateAbbr == "GA"),
             sum(E$StateAbbr == "HI"),
             sum(E$StateAbbr == "ID"),
              sum(E$StateAbbr == "IL"),
              sum(E$StateAbbr == "IN"),
             sum(E$StateAbbr == "IA"),
             sum(E$StateAbbr == "KS"),
             sum(E$StateAbbr == "KY"),
             sum(E$StateAbbr == "LA"),
             sum(E$StateAbbr == "ME"),
             sum(E$StateAbbr == "MD"),
              sum(E$StateAbbr == "MA"),
             sum(E$StateAbbr == "MI"),
             sum(E$StateAbbr == "MN"),
             sum(E$StateAbbr == "MS"),
              sum(E$StateAbbr == "MO"),
             sum(E$StateAbbr == "MT"),
             sum(E$StateAbbr == "NE"),
             sum(E$StateAbbr == "NV"),
             sum(E$StateAbbr == "NH"),
             sum(E$StateAbbr == "NJ"),
             sum(E$StateAbbr == "NM"),
              sum(E$StateAbbr == "NY"),
             sum(E$StateAbbr == "NC"),
             sum(E$StateAbbr == "ND"),
             sum(E$StateAbbr == "OH"),
             sum(E$StateAbbr == "OK"),
             sum(E$StateAbbr == "OR"),
             sum(E$StateAbbr == "PA"),
             sum(E$StateAbbr == "RI"),
              sum(E$StateAbbr == "SC"),
             sum(E$StateAbbr == "SD"),
              sum(E$StateAbbr == "TN"),
             sum(E$StateAbbr == "TX"),
             sum(E$StateAbbr == "UT"),
             sum(E$StateAbbr == "VT"),
              sum(E$StateAbbr == "VA"),
             sum(E$StateAbbr == "WA"),
             sum(E$StateAbbr == "WV"),
              sum(E$StateAbbr == "WI"),
             sum(E$StateAbbr == "WY")
)
Estates
Estates2 = c( sum(E$StateAbbr == "SC"),
              sum(E$StateAbbr == "IN"),
              sum(E$StateAbbr == "MO"),
              sum(E$StateAbbr == "TN"),
              sum(E$StateAbbr == "FL"),
              sum(E$StateAbbr == "MA"),
              sum(E$StateAbbr == "WI"),
              sum(E$StateAbbr == "IL"),
              sum(E$StateAbbr == "NY"),
              sum(E$StateAbbr == "VA")
)
barplot(Estates2, main="Education Top 10 States", xlab="States",
         ylab="Amount of Questions", names.arg=c("SC", "IN", "MO", "TN",
                                                 "FL", "MA", "WI", "IL",
                                                 "NY", "VA"),
         col = rainbow(10)
)
HDstates = c(sum(HD$StateAbbr == "AL"),
             sum(HD$StateAbbr == "AK"),
             sum(HD$StateAbbr == "AZ"),
             sum(HD$StateAbbr == "AR"),
             sum(HD$StateAbbr == "CA"),
             sum(HD$StateAbbr == "CO"),
             sum(HD$StateAbbr == "CT"),
             sum(HD$StateAbbr == "DE"),
             sum(HD$StateAbbr == "DC"),
              sum(HD$StateAbbr == "FL"),
             sum(HD$StateAbbr == "GA"),
             sum(HD$StateAbbr == "HI"),
             sum(HD$StateAbbr == "ID"),
              sum(HD$StateAbbr == "IL"),
              sum(HD$StateAbbr == "IN"),
             sum(HD$StateAbbr == "IA"),
             sum(HD$StateAbbr == "KS"),
             sum(HD$StateAbbr == "KY"),
             sum(HD$StateAbbr == "LA"),
             sum(HD$StateAbbr == "ME"),
             sum(HD$StateAbbr == "MD"),
              sum(HD$StateAbbr == "MA"),
             sum(HD$StateAbbr == "MI"),
             sum(HD$StateAbbr == "MN"),
             sum(HD$StateAbbr == "MS"),
              sum(HD$StateAbbr == "MO"),
             sum(HD$StateAbbr == "MT"),
             sum(HD$StateAbbr == "NE"),
             sum(HD$StateAbbr == "NV"),
             sum(HD$StateAbbr == "NH"),
             sum(HD$StateAbbr == "NJ"),
             sum(HD$StateAbbr == "NM"),
              sum(HD$StateAbbr == "NY"),
              sum(HD$StateAbbr == "NC"),
             sum(HD$StateAbbr == "ND"),
             sum(HD$StateAbbr == "OH"),
             sum(HD$StateAbbr == "OK"),
             sum(HD$StateAbbr == "OR"),
             sum(HD$StateAbbr == "PA"),
             sum(HD$StateAbbr == "RI"),
              sum(HD$StateAbbr == "SC"),
             sum(HD$StateAbbr == "SD"),
              sum(HD$StateAbbr == "TN"),
              sum(HD$StateAbbr == "TX"),
             sum(HD$StateAbbr == "UT"),
             sum(HD$StateAbbr == "VT"),
             sum(HD$StateAbbr == "VA"),
             sum(HD$StateAbbr == "WA"),
             sum(HD$StateAbbr == "WV"),
             sum(HD$StateAbbr == "WI"),
             sum(HD$StateAbbr == "WY")
             )
HDstates
HDstates2 = c(sum(HD$StateAbbr == "TX"),
              sum(HD$StateAbbr == "FL"),
              sum(HD$StateAbbr == "IN"),
              sum(HD$StateAbbr == "IL"),
              sum(HD$StateAbbr == "SC"),
              sum(HD$StateAbbr == "MO"),
              sum(HD$StateAbbr == "TN"),
              sum(HD$StateAbbr == "NC"),
              sum(HD$StateAbbr == "NY"),
              sum(HD$StateAbbr == "MA")
)
barplot(HDstates2, main="Health and Disability Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("TX", "FL", "IN", "IL",
                                                "SC", "MO", "TN", "NC",
                                                "NY", "MA"),
        col = rainbow(10)
)
Estates = c(sum(E$StateAbbr == "AL"),
             sum(E$StateAbbr == "AK"),
             sum(E$StateAbbr == "AZ"),
             sum(E$StateAbbr == "AR"),
             sum(E$StateAbbr == "CA"),
             sum(E$StateAbbr == "CO"),
             sum(E$StateAbbr == "CT"),
             sum(E$StateAbbr == "DE"),
             sum(E$StateAbbr == "DC"),
             sum(E$StateAbbr == "FL"),
             sum(E$StateAbbr == "GA"),
             sum(E$StateAbbr == "HI"),
             sum(E$StateAbbr == "ID"),
             sum(E$StateAbbr == "IL"),
             sum(E$StateAbbr == "IN"),
             sum(E$StateAbbr == "IA"),
             sum(E$StateAbbr == "KS"),
             sum(E$StateAbbr == "KY"),
             sum(E$StateAbbr == "LA"),
             sum(E$StateAbbr == "ME"),
             sum(E$StateAbbr == "MD"),
             sum(E$StateAbbr == "MA"),
             sum(E$StateAbbr == "MI"),
             sum(E$StateAbbr == "MN"),
             sum(E$StateAbbr == "MS"),
             sum(E$StateAbbr == "MO"),
             sum(E$StateAbbr == "MT"),
             sum(E$StateAbbr == "NE"),
             sum(E$StateAbbr == "NV"),
             sum(E$StateAbbr == "NH"),
             sum(E$StateAbbr == "NJ"),
             sum(E$StateAbbr == "NM"),
             sum(E$StateAbbr == "NY"),
             sum(E$StateAbbr == "NC"),
             sum(E$StateAbbr == "ND"),
             sum(E$StateAbbr == "OH"),
             sum(E$StateAbbr == "OK"),
             sum(E$StateAbbr == "OR"),
             sum(E$StateAbbr == "PA"),
             sum(E$StateAbbr == "RI"),
             sum(E$StateAbbr == "SC"),
             sum(E$StateAbbr == "SD"),
             sum(E$StateAbbr == "TN"),
             sum(E$StateAbbr == "TX"),
             sum(E$StateAbbr == "UT"),
             sum(E$StateAbbr == "VT"),
             sum(E$StateAbbr == "VA"),
             sum(E$StateAbbr == "WA"),
             sum(E$StateAbbr == "WV"),
             sum(E$StateAbbr == "WI"),
             sum(E$StateAbbr == "WY")
)
Estates
Estates2 = c( sum(E$StateAbbr == "SC"),
              sum(E$StateAbbr == "IN"),
              sum(E$StateAbbr == "MO"),
              sum(E$StateAbbr == "TN"),
              sum(E$StateAbbr == "FL"),
              sum(E$StateAbbr == "MA"),
              sum(E$StateAbbr == "WI"),
              sum(E$StateAbbr == "IL"),
              sum(E$StateAbbr == "NY"),
              sum(E$StateAbbr == "VA")
)
barplot(Estates2, main="Education Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("SC", "IN", "MO", "TN",
                                                "FL", "MA", "WI", "IL",
                                                "NY", "VA"),
        col = rainbow(10)
)
HHstates = c(sum(HH$StateAbbr == "AL"),
             sum(HH$StateAbbr == "AK"),
             sum(HH$StateAbbr == "AZ"),
             sum(HH$StateAbbr == "AR"),
             sum(HH$StateAbbr == "CA"),
             sum(HH$StateAbbr == "CO"),
             sum(HH$StateAbbr == "CT"),
             sum(HH$StateAbbr == "DE"),
             sum(HH$StateAbbr == "DC"),
              sum(HH$StateAbbr == "FL"),
              sum(HH$StateAbbr == "GA"),
             sum(HH$StateAbbr == "HI"),
             sum(HH$StateAbbr == "ID"),
              sum(HH$StateAbbr == "IL"),
              sum(HH$StateAbbr == "IN"),
             sum(HH$StateAbbr == "IA"),
             sum(HH$StateAbbr == "KS"),
             sum(HH$StateAbbr == "KY"),
             sum(HH$StateAbbr == "LA"),
             sum(HH$StateAbbr == "ME"),
             sum(HH$StateAbbr == "MD"),
              sum(HH$StateAbbr == "MA"),
             sum(HH$StateAbbr == "MI"),
             sum(HH$StateAbbr == "MN"),
             sum(HH$StateAbbr == "MS"),
              sum(HH$StateAbbr == "MO"),
             sum(HH$StateAbbr == "MT"),
             sum(HH$StateAbbr == "NE"),
             sum(HH$StateAbbr == "NV"),
             sum(HH$StateAbbr == "NH"),
             sum(HH$StateAbbr == "NJ"),
             sum(HH$StateAbbr == "NM"),
             sum(HH$StateAbbr == "NY"),
             sum(HH$StateAbbr == "NC"),
             sum(HH$StateAbbr == "ND"),
             sum(HH$StateAbbr == "OH"),
             sum(HH$StateAbbr == "OK"),
             sum(HH$StateAbbr == "OR"),
             sum(HH$StateAbbr == "PA"),
             sum(HH$StateAbbr == "RI"),
              sum(HH$StateAbbr == "SC"),
             sum(HH$StateAbbr == "SD"),
              sum(HH$StateAbbr == "TN"),
              sum(HH$StateAbbr == "TX"),
             sum(HH$StateAbbr == "UT"),
             sum(HH$StateAbbr == "VT"),
             sum(HH$StateAbbr == "VA"),
             sum(HH$StateAbbr == "WA"),
             sum(HH$StateAbbr == "WV"),
              sum(HH$StateAbbr == "WI"),
             sum(HH$StateAbbr == "WY")
             )
HHstates
HHstates2 = c(sum(HH$StateAbbr == "FL"),
               sum(HH$StateAbbr == "MA"),
               sum(HH$StateAbbr == "IN"),
               sum(HH$StateAbbr == "SC"),
               sum(HH$StateAbbr == "TX"),
               sum(HH$StateAbbr == "TN"),
               sum(HH$StateAbbr == "IL"),
               sum(HH$StateAbbr == "MO"),
               sum(HH$StateAbbr == "GA"),
               sum(HH$StateAbbr == "WI")
               )
barplot(HHstates2, main="Housing and Homelessness Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("FL", "MA", "IN", "SC",
                                                "TX", "TN", "IL", "MO",
                                                "GA", "WI"),
        col = rainbow(10)
)
IMstates = c(sum(IM$StateAbbr == "AL"),
             sum(IM$StateAbbr == "AK"),
             sum(IM$StateAbbr == "AZ"),
             sum(IM$StateAbbr == "AR"),
             sum(IM$StateAbbr == "CA"),
             sum(IM$StateAbbr == "CO"),
             sum(IM$StateAbbr == "CT"),
             sum(IM$StateAbbr == "DE"),
             sum(IM$StateAbbr == "DC"),
              sum(IM$StateAbbr == "FL"),
              sum(IM$StateAbbr == "GA"),
             sum(IM$StateAbbr == "HI"),
             sum(IM$StateAbbr == "ID"),
              sum(IM$StateAbbr == "IL"),
             sum(IM$StateAbbr == "IN"),
             sum(IM$StateAbbr == "IA"),
             sum(IM$StateAbbr == "KS"),
             sum(IM$StateAbbr == "KY"),
             sum(IM$StateAbbr == "LA"),
             sum(IM$StateAbbr == "ME"),
             sum(IM$StateAbbr == "MD"),
              sum(IM$StateAbbr == "MA"),
             sum(IM$StateAbbr == "MI"),
             sum(IM$StateAbbr == "MN"),
             sum(IM$StateAbbr == "MS"),
              sum(IM$StateAbbr == "MO"),
             sum(IM$StateAbbr == "MT"),
             sum(IM$StateAbbr == "NE"),
             sum(IM$StateAbbr == "NV"),
             sum(IM$StateAbbr == "NH"),
             sum(IM$StateAbbr == "NJ"),
             sum(IM$StateAbbr == "NM"),
              sum(IM$StateAbbr == "NY"),
             sum(IM$StateAbbr == "NC"),
             sum(IM$StateAbbr == "ND"),
             sum(IM$StateAbbr == "OH"),
             sum(IM$StateAbbr == "OK"),
             sum(IM$StateAbbr == "OR"),
             sum(IM$StateAbbr == "PA"),
             sum(IM$StateAbbr == "RI"),
              sum(IM$StateAbbr == "SC"),
             sum(IM$StateAbbr == "SD"),
              sum(IM$StateAbbr == "TN"),
              sum(IM$StateAbbr == "TX"),
             sum(IM$StateAbbr == "UT"),
             sum(IM$StateAbbr == "VT"),
              sum(IM$StateAbbr == "VA"),
             sum(IM$StateAbbr == "WA"),
             sum(IM$StateAbbr == "WV"),
             sum(IM$StateAbbr == "WI"),
             sum(IM$StateAbbr == "WY")
)
IMstates
IMstates2 = c(sum(IM$StateAbbr == "MA"),
              sum(IM$StateAbbr == "TN"),
              sum(IM$StateAbbr == "FL"),
              sum(IM$StateAbbr == "IL"),
              sum(IM$StateAbbr == "TX"),
              sum(IM$StateAbbr == "SC"),
              sum(IM$StateAbbr == "GA"),
              sum(IM$StateAbbr == "MO"),
              sum(IM$StateAbbr == "NY"),
              sum(IM$StateAbbr == "VA")
              )
barplot(IMstates2, main="Income Maintenance Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("MA", "TN", "FL", "IL",
                                                "TX", "SC", "GA", "MO",
                                                "NY", "VA"),
        col = rainbow(10)
)
CFQstate = c(sum(CFQ$StateAbbr == "AL"),
       sum(CFQ$StateAbbr == "AK"),
       sum(CFQ$StateAbbr == "AZ"),
       sum(CFQ$StateAbbr == "AR"),
       sum(CFQ$StateAbbr == "CA"),
       sum(CFQ$StateAbbr == "CO"),
       sum(CFQ$StateAbbr == "CT"),
       sum(CFQ$StateAbbr == "DE"),
       sum(CFQ$StateAbbr == "DC"),
        sum(CFQ$StateAbbr == "FL"),
       sum(CFQ$StateAbbr == "GA"),
       sum(CFQ$StateAbbr == "HI"),
       sum(CFQ$StateAbbr == "ID"),
        sum(CFQ$StateAbbr == "IL"),
        sum(CFQ$StateAbbr == "IN"),
       sum(CFQ$StateAbbr == "IA"),
       sum(CFQ$StateAbbr == "KS"),
       sum(CFQ$StateAbbr == "KY"),
       sum(CFQ$StateAbbr == "LA"),
       sum(CFQ$StateAbbr == "ME"),
       sum(CFQ$StateAbbr == "MD"),
        sum(CFQ$StateAbbr == "MA"),
       sum(CFQ$StateAbbr == "MI"),
       sum(CFQ$StateAbbr == "MN"),
       sum(CFQ$StateAbbr == "MS"),
        sum(CFQ$StateAbbr == "MO"),
       sum(CFQ$StateAbbr == "MT"),
       sum(CFQ$StateAbbr == "NE"),
       sum(CFQ$StateAbbr == "NV"),
       sum(CFQ$StateAbbr == "NH"),
       sum(CFQ$StateAbbr == "NJ"),
       sum(CFQ$StateAbbr == "NM"),
       sum(CFQ$StateAbbr == "NY"),
       sum(CFQ$StateAbbr == "NC"),
       sum(CFQ$StateAbbr == "ND"),
       sum(CFQ$StateAbbr == "OH"),
        sum(CFQ$StateAbbr == "OK"),
       sum(CFQ$StateAbbr == "OR"),
       sum(CFQ$StateAbbr == "PA"),
       sum(CFQ$StateAbbr == "RI"),
        sum(CFQ$StateAbbr == "SC"),
       sum(CFQ$StateAbbr == "SD"),
        sum(CFQ$StateAbbr == "TN"),
        sum(CFQ$StateAbbr == "TX"),
       sum(CFQ$StateAbbr == "UT"),
       sum(CFQ$StateAbbr == "VT"),
       sum(CFQ$StateAbbr == "VA"),
       sum(CFQ$StateAbbr == "WA"),
       sum(CFQ$StateAbbr == "WV"),
        sum(CFQ$StateAbbr == "WI"),
       sum(CFQ$StateAbbr == "WY")
)
CFQstate
CFQstate2 = c(sum(CFQ$StateAbbr == "IN"),
              sum(CFQ$StateAbbr == "TX"),
              sum(CFQ$StateAbbr == "IL"),
              sum(CFQ$StateAbbr == "FL"),
              sum(CFQ$StateAbbr == "TN"),
              sum(CFQ$StateAbbr == "SC"),
              sum(CFQ$StateAbbr == "MO"),
              sum(CFQ$StateAbbr == "WI"),
              sum(CFQ$StateAbbr == "MA"),
              sum(CFQ$StateAbbr == "OK")
              )
barplot(CFQstate2, main="Consumer Financial Question Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("IN", "TX", "IL", "FL",
                                                "TN", "SC", "MO", "WI",
                                                "MA", "OK"),
        col = rainbow(10)
)
Jstate = c(sum(J$StateAbbr == "AL"),
          sum(J$StateAbbr == "AK"),
          sum(J$StateAbbr == "AZ"),
          sum(J$StateAbbr == "AR"),
          sum(J$StateAbbr == "CA"),
          sum(J$StateAbbr == "CO"),
          sum(J$StateAbbr == "CT"),
          sum(J$StateAbbr == "DE"),
          sum(J$StateAbbr == "DC"),
           sum(J$StateAbbr == "FL"),
          sum(J$StateAbbr == "GA"),
          sum(J$StateAbbr == "HI"),
          sum(J$StateAbbr == "ID"),
           sum(J$StateAbbr == "IL"),
           sum(J$StateAbbr == "IN"),
          sum(J$StateAbbr == "IA"),
          sum(J$StateAbbr == "KS"),
          sum(J$StateAbbr == "KY"),
           sum(J$StateAbbr == "LA"),
          sum(J$StateAbbr == "ME"),
          sum(J$StateAbbr == "MD"),
          sum(J$StateAbbr == "MA"),
          sum(J$StateAbbr == "MI"),
          sum(J$StateAbbr == "MN"),
          sum(J$StateAbbr == "MS"),
           sum(J$StateAbbr == "MO"),
          sum(J$StateAbbr == "MT"),
           sum(J$StateAbbr == "NE"),
          sum(J$StateAbbr == "NV"),
          sum(J$StateAbbr == "NH"),
          sum(J$StateAbbr == "NJ"),
          sum(J$StateAbbr == "NM"),
           sum(J$StateAbbr == "NY"),
           sum(J$StateAbbr == "NC"),
          sum(J$StateAbbr == "ND"),
          sum(J$StateAbbr == "OH"),
          sum(J$StateAbbr == "OK"),
          sum(J$StateAbbr == "OR"),
          sum(J$StateAbbr == "PA"),
          sum(J$StateAbbr == "RI"),
          sum(J$StateAbbr == "SC"),
          sum(J$StateAbbr == "SD"),
           sum(J$StateAbbr == "TN"),
           sum(J$StateAbbr == "TX"),
          sum(J$StateAbbr == "UT"),
          sum(J$StateAbbr == "VT"),
          sum(J$StateAbbr == "VA"),
          sum(J$StateAbbr == "WA"),
          sum(J$StateAbbr == "WV"),
          sum(J$StateAbbr == "WI"),
          sum(J$StateAbbr == "WY")
)
Jstate
Jstate2 = c(sum(J$StateAbbr == "IN"),
            sum(J$StateAbbr == "NE"),
            sum(J$StateAbbr == "TX"),
            sum(J$StateAbbr == "IL"),
            sum(J$StateAbbr == "MO"),
            sum(J$StateAbbr == "FL"),
            sum(J$StateAbbr == "TN"),
            sum(J$StateAbbr == "LA"),
            sum(J$StateAbbr == "NY"),
            sum(J$StateAbbr == "NC")
            )
barplot(Jstate2, main="Juvenile Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("IN", "NE", "TX", "IL",
                                                "MO", "FL", "TN", "LA",
                                                "NY", "NC"),
        col = rainbow(10)
)
WEUstate = c(sum(WEU$StateAbbr == "AL"),
             sum(WEU$StateAbbr == "AK"),
             sum(WEU$StateAbbr == "AZ"),
             sum(WEU$StateAbbr == "AR"),
             sum(WEU$StateAbbr == "CA"),
             sum(WEU$StateAbbr == "CO"),
             sum(WEU$StateAbbr == "CT"),
             sum(WEU$StateAbbr == "DE"),
             sum(WEU$StateAbbr == "DC"),
              sum(WEU$StateAbbr == "FL"),
             sum(WEU$StateAbbr == "GA"),
             sum(WEU$StateAbbr == "HI"),
             sum(WEU$StateAbbr == "ID"),
              sum(WEU$StateAbbr == "IL"),
              sum(WEU$StateAbbr == "IN"),
             sum(WEU$StateAbbr == "IA"),
             sum(WEU$StateAbbr == "KS"),
             sum(WEU$StateAbbr == "KY"),
             sum(WEU$StateAbbr == "LA"),
             sum(WEU$StateAbbr == "ME"),
             sum(WEU$StateAbbr == "MD"),
              sum(WEU$StateAbbr == "MA"),
             sum(WEU$StateAbbr == "MI"),
             sum(WEU$StateAbbr == "MN"),
             sum(WEU$StateAbbr == "MS"),
              sum(WEU$StateAbbr == "MO"),
             sum(WEU$StateAbbr == "MT"),
             sum(WEU$StateAbbr == "NE"),
             sum(WEU$StateAbbr == "NV"),
             sum(WEU$StateAbbr == "NH"),
             sum(WEU$StateAbbr == "NJ"),
             sum(WEU$StateAbbr == "NM"),
             sum(WEU$StateAbbr == "NY"),
              sum(WEU$StateAbbr == "NC"),
             sum(WEU$StateAbbr == "ND"),
             sum(WEU$StateAbbr == "OH"),
             sum(WEU$StateAbbr == "OK"),
             sum(WEU$StateAbbr == "OR"),
             sum(WEU$StateAbbr == "PA"),
             sum(WEU$StateAbbr == "RI"),
              sum(WEU$StateAbbr == "SC"),
             sum(WEU$StateAbbr == "SD"),
              sum(WEU$StateAbbr == "TN"),
              sum(WEU$StateAbbr == "TX"),
             sum(WEU$StateAbbr == "UT"),
             sum(WEU$StateAbbr == "VT"),
             sum(WEU$StateAbbr == "VA"),
             sum(WEU$StateAbbr == "WA"),
             sum(WEU$StateAbbr == "WV"),
              sum(WEU$StateAbbr == "WI"),
             sum(WEU$StateAbbr == "WY")
)
WEUstate
WEUstate2 = c( sum(WEU$StateAbbr == "IL"),
               sum(WEU$StateAbbr == "SC"),
               sum(WEU$StateAbbr == "MA"),
               sum(WEU$StateAbbr == "TX"),
               sum(WEU$StateAbbr == "FL"),
               sum(WEU$StateAbbr == "IN"),
               sum(WEU$StateAbbr == "WI"),
               sum(WEU$StateAbbr == "MO"),
               sum(WEU$StateAbbr == "TN"),
               sum(WEU$StateAbbr == "NC")
               )
barplot(WEUstate2, main="Work, Employment and Unemployment Top 10 States", xlab="States",
        ylab="Amount of Questions", names.arg=c("IL", "SC", "MA", "TX",
                                                "FL", "IN", "WI", "MO",
                                                "TN", "NC"),
        col = rainbow(10)
)